---
abstract: 'Distribution builder, Opinionated but Unobtrusive'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Module::Build: '0.3601'
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.6, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Milla
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla: '4.300032'
  Dist::Zilla::Plugin::CheckChangesHasContent: '0'
  Dist::Zilla::Plugin::ConfirmRelease: '0'
  Dist::Zilla::Plugin::ContributorsFromGit: '0'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::CopyFilesFromRelease: '0'
  Dist::Zilla::Plugin::ExecDir: '0'
  Dist::Zilla::Plugin::ExtraTests: '0'
  Dist::Zilla::Plugin::Git::GatherDir: '0'
  Dist::Zilla::Plugin::Git::Init: '2.012'
  Dist::Zilla::Plugin::GithubMeta: '0'
  Dist::Zilla::Plugin::License: '0'
  Dist::Zilla::Plugin::LicenseFromModule: '0.05'
  Dist::Zilla::Plugin::Manifest: '0'
  Dist::Zilla::Plugin::MetaJSON: '0'
  Dist::Zilla::Plugin::MetaYAML: '0'
  Dist::Zilla::Plugin::ModuleBuildTiny: '0'
  Dist::Zilla::Plugin::NameFromDirectory: '0'
  Dist::Zilla::Plugin::NextRelease: '0'
  Dist::Zilla::Plugin::PodSyntaxTests: '0'
  Dist::Zilla::Plugin::Prereqs::FromCPANfile: '0.06'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0'
  Dist::Zilla::Plugin::ReadmeFromPod: '0'
  Dist::Zilla::Plugin::ReversionOnRelease: '0.04'
  Dist::Zilla::Plugin::ShareDir: '0'
  Dist::Zilla::Plugin::Test::Compile: '0'
  Dist::Zilla::Plugin::TestRelease: '0'
  Dist::Zilla::Plugin::UploadToCPAN: '0'
  Dist::Zilla::Plugin::VersionFromModule: '0'
  Dist::Zilla::PluginBundle::Git: '0'
  Dist::Zilla::Role::PluginBundle::Config::Slicer: '0'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0'
  Module::CPANfile: '0.9025'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/miyagawa/Dist-Milla/issues
  homepage: https://github.com/miyagawa/Dist-Milla
  repository: https://github.com/miyagawa/Dist-Milla.git
version: v1.0.8
x_contributors:
  - 'Curtis Brandt <curtis@cpan.org>'
  - 'Helmut Wollmersdorfer <helmut@wollmersdorfer.at>'
  - 'Mike Greb <mikegrb@cpan.org>'
  - 'Olivier Mengué <dolmen@cpan.org>'
  - 'Shawn M Moore <code@sartak.org>'
  - 'Tatsuhiko Miyagawa <miyagawa@gmail.com>'
