---
abstract: 'Distribution builder, Opinionated but Unobtrusive'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v0.9.0, Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Milla
requires:
  Dist::Zilla: 4.300025
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0
  Dist::Zilla::Plugin::CopyFilesFromRelease: 0
  Dist::Zilla::Plugin::ExecDir: 0
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::Git::GatherDir: 0
  Dist::Zilla::Plugin::Git::Init: 2.012
  Dist::Zilla::Plugin::GithubMeta: 0
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::LicenseFromModule: 0
  Dist::Zilla::Plugin::Manifest: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::ModuleBuildTiny: 0
  Dist::Zilla::Plugin::NameFromDirectory: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::Prereqs::FromCPANfile: 0
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::ReversionOnRelease: 0
  Dist::Zilla::Plugin::ShareDir: 0
  Dist::Zilla::Plugin::Test::Compile: 0
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::Plugin::VersionFromModule: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Config::Slicer: 0
  Module::CPANfile: 0.9025
  perl: 5.008005
resources:
  bugtracker: https://github.com/miyagawa/Dist-Milla/issues
  homepage: https://github.com/miyagawa/Dist-Milla
  repository: https://github.com/miyagawa/Dist-Milla.git
version: v0.9.1
